name: main
on: 
  pull_request:
  push:
    branches:
      - "*"
jobs:
  test:
    env:
      LATEST_GO: 1.19.x # version used for release
    strategy:
      matrix:
        go: [ 1.19.x ]
        os: [ ubuntu-latest ]
        arch:
        - arm64
        - amd64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - run: make test
  test_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
        - arm64
        - amd64
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - run: make create ARCH=${{ matrix.arch }}

  test_merge:
    runs-on: ubuntu-latest
    needs:
      - test_build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:$(shell git describe --tags --exact-match 2> /dev/null || echo dev)

          docker manifest create $IMAGE_NAME \
            --amend $IMAGE_NAME-arm64 \
            --amend $IMAGE_NAME-amd64

          docker manifest annotate --arch amd64 $IMAGE_NAME \
            $IMAGE_NAME-amd64

          docker manifest annotate --arch arm64 $IMAGE_NAME \
            $IMAGE_NAME-arm64

          docker manifest inspect $IMAGE_NAME