name: Production Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    env:
      LATEST_GO: 1.19.x # version used for release
    strategy:
      matrix:
        go: [ 1.19.x ]
        os: [ ubuntu-latest ]
    name: ${{ matrix.os }}/go${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - run: make test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - run: |
          make create PLUGIN_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.repository }} PLUGIN_TAG=$RELEASE_VERSION-arm64 ARCH=arm64
          make create PLUGIN_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.repository }} PLUGIN_TAG=$RELEASE_VERSION-amd64 ARCH=amd64

      - run: |
          docker manifest create ghcr.io/${{ github.repository_owner }}/${{ github.repository }} \
            --amend ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-$RELEASE_VERSION-arm64 \
            --amend ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-$RELEASE_VERSION-amd64
          
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
